# -----------------------------
# Options (maybe put as args)
# -----------------------------
alignmentOption: 0 # 0 - dense to dense, 1 - keypoints to dense, 2 - keypoints to keypoints
bShowAlignment: false
localisationOption: 2 # Option for localisation method (0 - PCL, 1 - RANSAC IA, 2 - Prerejective RANSAC)
keypointOption: 0
processRate: 10.0

machine: 1

bRejectNonOverlappingInAlign: false # whether or not to reject non-overlapping points before alignment

bPublishNurbsPointCloud: true # whether or not to publish the point cloud for visualuisation in Rviz

bTestMapGeneration: false

bLocalisationRejectionOn: false

mappingSteps: 5

bUseObjectMaskSegmentation: true

# -----------------------------
# Localisation
# -----------------------------
# Keypoints
/keypoints/modelResolution: 0.01
/keypoints/minNeighbours: 5

# Normals
pclNormalRadiusSetting: 0.25
# Features
pclFeatureRadiusSetting: 0.35
# RANSAC
/ransac/inlierMultiplier: 0.025
/ransac/maximumIterations: 7000 # 5000

# POSSIBLY USE
/ransac/numberOfSamples: 3
/ransac/correspondenceRandomness: 3
/ransac/similarityThreshold: 0.9
/ransac/inlierFraction: 0.6 # this should maybe be more strict for the blender data

validInlierThreshold: 0.6

maxDistanceOverlap: 0.05 # maximum allowed distance away from existing surface to not be classed as new data

# Number of data points
nSurfPointsFactor: 5.0 #6.0 # multiplier by the number of control points to get the number of surface points to sample

mapCountThreshold: 3
mapExtendThreshold: 100 # Make this very high to turn off the "new object when no extension for too long" feature

# -----------------------------
# Mapping
# -----------------------------
# Mesh processing
/meshing/numRowsDesired: 115
/meshing/numColsDesired: 115
/meshing/maxNanAllowed: 5
/meshing/removeNanBuffer: 4 # 2
/meshing/newRowColBuffer: 10 # Good for mapping - 20

/meshing/exitOnlyOnMinNans: false
/meshing/minRowsColsAllowed: 15
/meshing/maxNanPercentage: 0.25

/meshing/bFilterZ: true
/meshing/nPointsZLim: 10000
/meshing/zThreshMultiplier: 1.0
/meshing/bNegateZ: false

# NURBS generation
/mapping/useNonRectData: true # To use the new extension method
/mapping/nCtrlDefaultS: 25
/mapping/nCtrlDefaultR: 25
/mapping/degree: 3

# Data association
/mapping/searchThresh: 50.0 # capture everything for 67p

/mapping/bUseFullAlignmentTransformInUpdate: true
/mapping/bUseOldStateForNewObjects: true


# -----------------------------
# EKF
# -----------------------------
/ekf/pNoisePos: 5.0
/ekf/pNoiseVel: 0.0025
/ekf/pNoiseAccel: 0.00025
/ekf/pNoiseAng: 40000.0
/ekf/qNoiseMultiplier: 3.0 
/ekf/pNoiseMultiplier: 1.0
/ekf/noiseObsBasePos: 0.001 
/ekf/noiseObsMultPos: 500.0
/ekf/noiseObsMultPosErr: 1000.0
/ekf/noiseObsBaseAng: 0.00001
/ekf/noiseObsMultAng: 2500.0
/ekf/noiseObsMultAngErr: 50000.0 
/ekf/rMatMultiplier: 2375.0

/ekf/bKeepPConstant: false

/ekf/timestep: 20.0 # For data-based cases

/ekf/processModel: 0 # 0 - const accel, 1 - const vel, 2 - const pos

/ekf/rejectCriteriaAng: 1.2
/ekf/rejectCriteriaLin: 3.0
/ekf/rejectCriteriaInlier: 0.4
/ekf/rejectCriteriaNumberP: 0.25

# No filter settings
# /ekf/pNoisePos: 3.0
# /ekf/pNoiseVel: 3.0
# /ekf/pNoiseAccel: 3.0
# /ekf/pNoiseAng: 3.0
# /ekf/qNoiseMultiplier: 3.0
# /ekf/noiseObsBasePos: 0.000000001
# /ekf/noiseObsMultPos: 0.0
# /ekf/noiseObsBaseAng: 0.000000001
# /ekf/noiseObsMultAng: 0.0

